webtalk_init -webtalk_dir C:\\Users\\Albert\\Documents\\GitHub\\ECE532\\test_system\\vivado_proj\\Nexys-Video-HDMI.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2024-02-13 01:18:54" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "f75r3l1g532ct64nhgj3d24vh2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.2_2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "12th Gen Intel(R) Core(TM) i9-12900K" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3187 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.118 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1707799250958" -context "sdk\\\\hardware/1707799250958"
webtalk_add_data -client sdk -key isZynq -value "false" -context "sdk\\\\hardware/1707799250958"
webtalk_add_data -client sdk -key isZynqMP -value "false" -context "sdk\\\\hardware/1707799250958"
webtalk_add_data -client sdk -key Processors -value "1" -context "sdk\\\\hardware/1707799250958"
webtalk_add_data -client sdk -key VivadoVersion -value "2018.2" -context "sdk\\\\hardware/1707799250958"
webtalk_add_data -client sdk -key Arch -value "artix7" -context "sdk\\\\hardware/1707799250958"
webtalk_add_data -client sdk -key Device -value "7a200t" -context "sdk\\\\hardware/1707799250958"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1707799250958"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1707799250958"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1707799250958"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1707799250958"
webtalk_add_data -client sdk -key uid -value "1707799333032" -context "sdk\\\\bsp/1707799333032"
webtalk_add_data -client sdk -key hwid -value "1707799250958" -context "sdk\\\\bsp/1707799333032"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1707799333032"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\bsp/1707799333032"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1707799333032"
webtalk_add_data -client sdk -key uid -value "1707799335326" -context "sdk\\\\application/1707799335326"
webtalk_add_data -client sdk -key hwid -value "1707799250958" -context "sdk\\\\application/1707799335326"
webtalk_add_data -client sdk -key bspid -value "1707799333032" -context "sdk\\\\application/1707799335326"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1707799335326"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1707799335326"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1707799335326"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1707799335326"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1707799335326"
webtalk_add_data -client sdk -key Procused -value "microblaze" -context "sdk\\\\application/1707799335326"
webtalk_add_data -client sdk -key projSize -value "384.078125" -context "sdk\\\\application/1707799335326"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1707805134578"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1707805134578"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1707805134578"
webtalk_add_data -client sdk -key DebugCount -value "6" -context "sdk\\\\bsp/1707805134578"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1707805134578"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1707805134578"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1707805134578"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1707805134578"
webtalk_transmit -clientid 1177683274 -regid "" -xml C:\\Users\\Albert\\Documents\\GitHub\\ECE532\\test_system\\vivado_proj\\Nexys-Video-HDMI.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Users\\Albert\\Documents\\GitHub\\ECE532\\test_system\\vivado_proj\\Nexys-Video-HDMI.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Users\\Albert\\Documents\\GitHub\\ECE532\\test_system\\vivado_proj\\Nexys-Video-HDMI.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
