# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ece532/ECE532/test_system/vivado_proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_xbar_0/hdmi_xbar_0.xci
# IP: The module: 'hdmi_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ece532/ECE532/test_system/vivado_proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_xbar_0/hdmi_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/ece532/ECE532/test_system/vivado_proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_xbar_0/hdmi_xbar_0.xci
# IP: The module: 'hdmi_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ece532/ECE532/test_system/vivado_proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_xbar_0/hdmi_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
