# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/yunhao/Documents/ECE532-Digital-Systems-Design/ECE532-main/custom_ip/superresolution/superresolution.srcs/sources_1/ip/xbip_dsp48_macro_1/xbip_dsp48_macro_1.xci
# IP: The module: 'xbip_dsp48_macro_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/yunhao/Documents/ECE532-Digital-Systems-Design/ECE532-main/custom_ip/superresolution/superresolution.srcs/sources_1/ip/xbip_dsp48_macro_1/xbip_dsp48_macro_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xbip_dsp48_macro_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/yunhao/Documents/ECE532-Digital-Systems-Design/ECE532-main/custom_ip/superresolution/superresolution.srcs/sources_1/ip/xbip_dsp48_macro_1/xbip_dsp48_macro_1.xci
# IP: The module: 'xbip_dsp48_macro_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/yunhao/Documents/ECE532-Digital-Systems-Design/ECE532-main/custom_ip/superresolution/superresolution.srcs/sources_1/ip/xbip_dsp48_macro_1/xbip_dsp48_macro_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xbip_dsp48_macro_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
