#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2018.2.2 (64-bit)
#
# Filename    : hdmi.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Tue Apr 02 00:05:36 -0400 2024
# SW Build 2348494 on Mon Oct  1 18:25:44 MDT 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved. 
#
# usage: hdmi.sh [-help]
# usage: hdmi.sh [-lib_map_path]
# usage: hdmi.sh [-noclean_files]
# usage: hdmi.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'hdmi.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xil_defaultlib xpm axi_lite_ipif_v3_0_4 lib_cdc_v1_0_2 interrupt_control_v3_1_4 axi_gpio_v2_0_19 lib_pkg_v1_0_2 axi_timer_v2_0_19 lib_srl_fifo_v1_0_2 axi_uartlite_v2_0_21 fifo_generator_v13_2_2 lib_fifo_v1_0_11 blk_mem_gen_v8_4_1 lib_bmg_v1_0_10 axi_datamover_v5_1_19 axi_vdma_v6_3_5 mdm_v3_2_14 microblaze_v10_0_7 axi_intc_v4_1_11 xlconcat_v2_1_1 proc_sys_reset_v5_0_12 v_tc_v6_1_12 v_vid_in_axi4s_v4_0_8 v_axi4s_vid_out_v4_0_9 xlconstant_v1_1_5 lmb_bram_if_cntlr_v4_0_15 lmb_v10_v3_0_9 generic_baseblocks_v2_1_0 axi_infrastructure_v1_1_0 axi_register_slice_v2_1_17 axi_data_fifo_v2_1_16 axi_crossbar_v2_1_18 axi_sg_v4_1_10 axi_dma_v7_1_18)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "hdmi.sh - Script generated by export_simulation (Vivado v2018.2.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/b65a" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ca12/imports/sources" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ca12/imports/sources/srcnn/small" \
    "C:/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "C:/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "C:/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "C:/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/b65a" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ca12/imports/sources" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ca12/imports/sources/srcnn/small" \
    "$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/9097/src/mmcme2_drp.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/9097/src/axi_dynclk_S00_AXI.vhd" \
    "$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/9097/src/axi_dynclk.vhd" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_axi_dynclk_0_0/sim/hdmi_axi_dynclk_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/cced/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work interrupt_control_v3_1_4 $vhdlan_opts \
    "$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/8e66/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_gpio_v2_0_19 $vhdlan_opts \
    "$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/c193/hdl/axi_gpio_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_axi_gpio_video_0/sim/hdmi_axi_gpio_video_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_timer_v2_0_19 $vhdlan_opts \
    "$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/0a2c/hdl/axi_timer_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_axi_timer_0_0/sim/hdmi_axi_timer_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_uartlite_v2_0_21 $vhdlan_opts \
    "$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/a15e/hdl/axi_uartlite_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_axi_uartlite_0_0/sim/hdmi_axi_uartlite_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/b65a" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ca12/imports/sources" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ca12/imports/sources/srcnn/small" \
    "$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/7aff/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_2 $vhdlan_opts \
    "$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/7aff/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/b65a" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ca12/imports/sources" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ca12/imports/sources/srcnn/small" \
    "$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/7aff/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_fifo_v1_0_11 $vhdlan_opts \
    "$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/6078/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work blk_mem_gen_v8_4_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/b65a" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ca12/imports/sources" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ca12/imports/sources/srcnn/small" \
    "$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/67d8/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_bmg_v1_0_10 $vhdlan_opts \
    "$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/9340/hdl/lib_bmg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_datamover_v5_1_19 $vhdlan_opts \
    "$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ec8a/hdl/axi_datamover_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_vdma_v6_3_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/b65a" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ca12/imports/sources" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ca12/imports/sources/srcnn/small" \
    "$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/b37e/hdl/axi_vdma_v6_3_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_vdma_v6_3_5 $vhdlan_opts \
    "$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/b37e/hdl/axi_vdma_v6_3_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_axi_vdma_0_0/sim/hdmi_axi_vdma_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/b65a" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ca12/imports/sources" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ca12/imports/sources/srcnn/small" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_refclk/sim/ila_refclk.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_pixclk/sim/ila_pixclk.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/be44/src/SyncBase.vhd" \
    "$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/be44/src/EEPROM_8b.vhd" \
    "$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/be44/src/TWI_SlaveCtl.vhd" \
    "$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/be44/src/GlitchFilter.vhd" \
    "$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/be44/src/SyncAsync.vhd" \
    "$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/be44/src/DVI_Constants.vhd" \
    "$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/be44/src/SyncAsyncReset.vhd" \
    "$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/be44/src/PhaseAlign.vhd" \
    "$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/be44/src/InputSERDES.vhd" \
    "$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/be44/src/ChannelBond.vhd" \
    "$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/be44/src/ResyncToBUFG.vhd" \
    "$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/be44/src/TMDS_Decoder.vhd" \
    "$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/be44/src/TMDS_Clocking.vhd" \
    "$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/be44/src/dvi2rgb.vhd" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_dvi2rgb_0_0/sim/hdmi_dvi2rgb_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work mdm_v3_2_14 $vhdlan_opts \
    "$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/5125/hdl/mdm_v3_2_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mdm_1_0/sim/hdmi_mdm_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work microblaze_v10_0_7 $vhdlan_opts \
    "$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/b649/hdl/microblaze_v10_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_microblaze_0_0/sim/hdmi_microblaze_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_intc_v4_1_11 $vhdlan_opts \
    "$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/2fec/hdl/axi_intc_v4_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_microblaze_0_axi_intc_0/sim/hdmi_microblaze_0_axi_intc_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlconcat_v2_1_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/b65a" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ca12/imports/sources" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ca12/imports/sources/srcnn/small" \
    "$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/2f66/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/b65a" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ca12/imports/sources" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ca12/imports/sources/srcnn/small" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_microblaze_0_xlconcat_0/sim/hdmi_microblaze_0_xlconcat_0.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_1_axi_ctrl_addr_decode.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_1_axi_ctrl_read.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_1_axi_ctrl_reg.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_1_axi_ctrl_reg_bank.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_1_axi_ctrl_top.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_1_axi_ctrl_write.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_1_axi_mc.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_1_axi_mc_ar_channel.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_1_axi_mc_aw_channel.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_1_axi_mc_b_channel.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_1_axi_mc_cmd_arbiter.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_1_axi_mc_cmd_fsm.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_1_axi_mc_cmd_translator.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_1_axi_mc_fifo.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_1_axi_mc_incr_cmd.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_1_axi_mc_r_channel.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_1_axi_mc_simple_fifo.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_1_axi_mc_wrap_cmd.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_1_axi_mc_wr_cmd_fsm.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_1_axi_mc_w_channel.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_1_ddr_axic_register_slice.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_1_ddr_axi_register_slice.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_1_ddr_axi_upsizer.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_1_ddr_a_upsizer.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_1_ddr_carry_and.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_1_ddr_carry_latch_and.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_1_ddr_carry_latch_or.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_1_ddr_carry_or.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_1_ddr_command_fifo.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_1_ddr_comparator.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_1_ddr_comparator_sel.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_1_ddr_comparator_sel_static.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_1_ddr_r_upsizer.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_1_ddr_w_upsizer.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/clocking/mig_7series_v4_1_clk_ibuf.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/clocking/mig_7series_v4_1_infrastructure.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/clocking/mig_7series_v4_1_iodelay_ctrl.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/clocking/mig_7series_v4_1_tempmon.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_1_arb_mux.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_1_arb_row_col.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_1_arb_select.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_1_bank_cntrl.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_1_bank_common.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_1_bank_compare.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_1_bank_mach.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_1_bank_queue.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_1_bank_state.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_1_col_mach.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_1_mc.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_1_rank_cntrl.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_1_rank_common.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_1_rank_mach.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_1_round_robin_arb.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/ecc/mig_7series_v4_1_ecc_buf.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/ecc/mig_7series_v4_1_ecc_dec_fix.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/ecc/mig_7series_v4_1_ecc_gen.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/ecc/mig_7series_v4_1_ecc_merge_enc.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/ecc/mig_7series_v4_1_fi_xor.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/ip_top/mig_7series_v4_1_memc_ui_top_axi.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/ip_top/mig_7series_v4_1_mem_intfc.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_1_ddr_byte_group_io.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_1_ddr_byte_lane.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_1_ddr_calib_top.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_1_ddr_if_post_fifo.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_1_ddr_mc_phy.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_1_ddr_mc_phy_wrapper.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_1_ddr_of_pre_fifo.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_4lanes.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_ck_addr_cmd_delay.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_dqs_found_cal.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_dqs_found_cal_hr.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_init.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_ocd_cntlr.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_ocd_data.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_ocd_edge.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_ocd_lim.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_ocd_mux.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_ocd_po_cntlr.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_ocd_samp.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_oclkdelay_cal.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_prbs_rdlvl.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_rdlvl.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_tempmon.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_top.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_wrcal.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_wrlvl.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_wrlvl_off_delay.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_1_ddr_prbs_gen.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_1_ddr_skip_calib_tap.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_1_poc_cc.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_1_poc_edge_store.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_1_poc_meta.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_1_poc_pd.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_1_poc_tap_base.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_1_poc_top.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/ui/mig_7series_v4_1_ui_cmd.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/ui/mig_7series_v4_1_ui_rd_data.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/ui/mig_7series_v4_1_ui_top.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/ui/mig_7series_v4_1_ui_wr_data.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/hdmi_mig_7series_0_0_mig_sim.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/rtl/hdmi_mig_7series_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/20df/src/ClockGen.vhd" \
    "$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/20df/src/OutputSERDES.vhd" \
    "$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/20df/src/TMDS_Encoder.vhd" \
    "$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/20df/src/rgb2dvi.vhd" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_rgb2dvi_0_0/sim/hdmi_rgb2dvi_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_12 $vhdlan_opts \
    "$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/f86a/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_rst_mig_7series_0_100M_0/sim/hdmi_rst_mig_7series_0_100M_0.vhd" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_rst_mig_7series_0_pxl_0/sim/hdmi_rst_mig_7series_0_pxl_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work v_tc_v6_1_12 $vhdlan_opts \
    "$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/6694/hdl/v_tc_v6_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work v_vid_in_axi4s_v4_0_8 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/b65a" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ca12/imports/sources" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ca12/imports/sources/srcnn/small" \
    "$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/d987/hdl/v_vid_in_axi4s_v4_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work v_axi4s_vid_out_v4_0_9 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/b65a" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ca12/imports/sources" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ca12/imports/sources/srcnn/small" \
    "$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/9a07/hdl/v_axi4s_vid_out_v4_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/b65a" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ca12/imports/sources" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ca12/imports/sources/srcnn/small" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_v_axi4s_vid_out_0_0/sim/hdmi_v_axi4s_vid_out_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_v_tc_0_0/sim/hdmi_v_tc_0_0.vhd" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_v_tc_1_0/sim/hdmi_v_tc_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/b65a" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ca12/imports/sources" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ca12/imports/sources/srcnn/small" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_v_vid_in_axi4s_0_0/sim/hdmi_v_vid_in_axi4s_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconstant_v1_1_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/b65a" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ca12/imports/sources" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ca12/imports/sources/srcnn/small" \
    "$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/f1c3/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/b65a" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ca12/imports/sources" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ca12/imports/sources/srcnn/small" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_xlconstant_0_0/sim/hdmi_xlconstant_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lmb_bram_if_cntlr_v4_0_15 $vhdlan_opts \
    "$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/92fd/hdl/lmb_bram_if_cntlr_v4_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_dlmb_bram_if_cntlr_0/sim/hdmi_dlmb_bram_if_cntlr_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lmb_v10_v3_0_9 $vhdlan_opts \
    "$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/78eb/hdl/lmb_v10_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_dlmb_v10_0/sim/hdmi_dlmb_v10_0.vhd" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_ilmb_bram_if_cntlr_0/sim/hdmi_ilmb_bram_if_cntlr_0.vhd" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_ilmb_v10_0/sim/hdmi_ilmb_v10_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/b65a" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ca12/imports/sources" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ca12/imports/sources/srcnn/small" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_lmb_bram_0/sim/hdmi_lmb_bram_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/b65a" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ca12/imports/sources" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ca12/imports/sources/srcnn/small" \
    "$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/b65a" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ca12/imports/sources" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ca12/imports/sources/srcnn/small" \
    "$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_17 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/b65a" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ca12/imports/sources" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ca12/imports/sources/srcnn/small" \
    "$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/6020/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_16 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/b65a" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ca12/imports/sources" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ca12/imports/sources/srcnn/small" \
    "$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/247d/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_18 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/b65a" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ca12/imports/sources" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ca12/imports/sources/srcnn/small" \
    "$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/15a3/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/b65a" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ca12/imports/sources" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ca12/imports/sources/srcnn/small" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_xbar_1/sim/hdmi_xbar_1.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_xbar_0/sim/hdmi_xbar_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_sg_v4_1_10 $vhdlan_opts \
    "$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/6e5f/hdl/axi_sg_v4_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_dma_v7_1_18 $vhdlan_opts \
    "$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/6bfe/hdl/axi_dma_v7_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_axi_dma_0_0/sim/hdmi_axi_dma_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/b65a" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ca12/imports/sources" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ca12/imports/sources/srcnn/small" \
    "$ref_dir/../../../bd/hdmi/ipshared/b519/passthrough.sv" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_passthrough_0_0_1/sim/hdmi_passthrough_0_0.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_axi_dma_2_0/sim/hdmi_axi_dma_2_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/b65a" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ca12/imports/sources" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ca12/imports/sources/srcnn/small" \
    "$ref_dir/../../../../../../Users/Albert/Documents/GitHub/ECE532/custom_ip/stream2rgb/stream2rgb.srcs/sources_1/new/stream2rgb_top.sv" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_stream2rgb_0_0/sim/hdmi_stream2rgb_0_0.sv" \
    "$ref_dir/../../../../../../Users/Albert/Documents/GitHub/ECE532/custom_ip/rgb2stream/rgb2stream.srcs/sources_1/new/rgb2stream_top.sv" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_rgb2stream_0_0/sim/hdmi_rgb2stream_0_0.sv" \
    "$ref_dir/../../../bd/hdmi/ipshared/d4bf/grayscale.sv" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_grayscale_0_0/sim/hdmi_grayscale_0_0.sv" \
    "$ref_dir/../../../bd/hdmi/ipshared/349f/brightness.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/b65a" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ca12/imports/sources" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ca12/imports/sources/srcnn/small" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_brightening_0_0/sim/hdmi_brightening_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/b65a" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ca12/imports/sources" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ca12/imports/sources/srcnn/small" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_rgb2stream_1_0/sim/hdmi_rgb2stream_1_0.sv" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_stream2rgb_1_0/sim/hdmi_stream2rgb_1_0.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_axi_dma_2_1/sim/hdmi_axi_dma_2_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/b65a" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ca12/imports/sources" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ca12/imports/sources/srcnn/small" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_rgb2stream_1_1/sim/hdmi_rgb2stream_1_1.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_axi_dma_3_0/sim/hdmi_axi_dma_3_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/b65a" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ca12/imports/sources" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ca12/imports/sources/srcnn/small" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_stream2rgb_1_1/sim/hdmi_stream2rgb_1_1.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_axi_dma_4_0/sim/hdmi_axi_dma_4_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/b65a" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ca12/imports/sources" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ca12/imports/sources/srcnn/small" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_rgb2stream_2_0/sim/hdmi_rgb2stream_2_0.sv" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_stream2rgb_2_0/sim/hdmi_stream2rgb_2_0.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_axi_timer_1_1/sim/hdmi_axi_timer_1_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/b65a" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ca12/imports/sources" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ca12/imports/sources/srcnn/small" \
    "$ref_dir/../../../bd/hdmi/ipshared/8f9f/adder_tree.sv" \
    "$ref_dir/../../../bd/hdmi/ipshared/8f9f/utilities.svh" \
    "$ref_dir/../../../bd/hdmi/ipshared/8f9f/channelwise_convolve.sv" \
    "$ref_dir/../../../bd/hdmi/ipshared/8f9f/constant_pad.sv" \
    "$ref_dir/../../../bd/hdmi/ipshared/8f9f/dual_port_ram.sv" \
    "$ref_dir/../../../bd/hdmi/ipshared/8f9f/sliding_window.sv" \
    "$ref_dir/../../../bd/hdmi/ipshared/8f9f/convolution.sv" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_convolution_0_0_1/sim/hdmi_convolution_0_0.sv" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_convolution_0_1/sim/hdmi_convolution_0_1.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/b65a" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ca12/imports/sources" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ca12/imports/sources/srcnn/small" \
    "$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_superresolution_0_0_1/hdmi_superresolution_0_0_sim_netlist.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/b65a" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ca12/imports/sources" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ca12/imports/sources/srcnn/small" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_rgb2stream_2_1/sim/hdmi_rgb2stream_2_1.sv" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_stream2rgb_2_1/sim/hdmi_stream2rgb_2_1.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_axi_dma_4_1/sim/hdmi_axi_dma_4_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/b65a" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ca12/imports/sources" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ca12/imports/sources/srcnn/small" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_clk_wiz_0_0/hdmi_clk_wiz_0_0_clk_wiz.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_clk_wiz_0_0/hdmi_clk_wiz_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_axi_gpio_0_1/sim/hdmi_axi_gpio_0_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/b65a" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ca12/imports/sources" +incdir+"$ref_dir/../../../../Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ipshared/ca12/imports/sources/srcnn/small" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_m00_regslice_0/hdmi_m00_regslice_0_sim_netlist.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_auto_ds_0/hdmi_auto_ds_0_sim_netlist.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_auto_rs_w_0/hdmi_auto_rs_w_0_sim_netlist.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_auto_us_11_1/hdmi_auto_us_11_sim_netlist.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_auto_us_10_1/hdmi_auto_us_10_sim_netlist.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_auto_us_9/hdmi_auto_us_9_sim_netlist.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_auto_us_8/hdmi_auto_us_8_sim_netlist.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_auto_us_7/hdmi_auto_us_7_sim_netlist.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_auto_us_6/hdmi_auto_us_6_sim_netlist.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_auto_us_5/hdmi_auto_us_5_sim_netlist.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_auto_us_4/hdmi_auto_us_4_sim_netlist.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_auto_us_3/hdmi_auto_us_3_sim_netlist.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_auto_us_2/hdmi_auto_us_2_sim_netlist.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_s03_regslice_0/hdmi_s03_regslice_0_sim_netlist.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_s02_regslice_0/hdmi_s02_regslice_0_sim_netlist.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_s01_regslice_0/hdmi_s01_regslice_0_sim_netlist.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_auto_us_1/hdmi_auto_us_1_sim_netlist.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_auto_rs_w_2/hdmi_auto_rs_w_2_sim_netlist.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_s00_regslice_0/hdmi_s00_regslice_0_sim_netlist.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_auto_us_0/hdmi_auto_us_0_sim_netlist.v" \
    "$ref_dir/../../../bd/hdmi/ip/hdmi_auto_rs_w_1/hdmi_auto_rs_w_1_sim_netlist.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.hdmi xil_defaultlib.glbl -o hdmi_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./hdmi_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./hdmi.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key hdmi_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc hdmi_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./hdmi.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: hdmi.sh [-help]\n\
Usage: hdmi.sh [-lib_map_path]\n\
Usage: hdmi.sh [-reset_run]\n\
Usage: hdmi.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
