all:
	vivado -mode batch -source srcnn_rgb.tcl -nojournal -nolog

clean:
	rm -rf .Xil xgui component.xml \
		srcnn_rgb.xpr \
		srcnn_rgb.cache \
		srcnn_rgb.hw \
		srcnn_rgb.ip_user_files \
		srcnn_rgb.sim \
		srcnn_rgb.srcs
