# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/yunhao/Documents/ECE532-Digital-Systems-Design/ECE532-main/custom_ip/superresolution/superresolution.srcs/sources_1/ip/axis_data_fifo_0/axis_data_fifo_0.xci
# IP: The module: 'axis_data_fifo_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/yunhao/Documents/ECE532-Digital-Systems-Design/ECE532-main/custom_ip/superresolution/superresolution.srcs/sources_1/ip/axis_data_fifo_0/axis_data_fifo_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_data_fifo_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/yunhao/Documents/ECE532-Digital-Systems-Design/ECE532-main/custom_ip/superresolution/superresolution.srcs/sources_1/ip/axis_data_fifo_0/axis_data_fifo_0/axis_data_fifo_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_data_fifo_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/yunhao/Documents/ECE532-Digital-Systems-Design/ECE532-main/custom_ip/superresolution/superresolution.srcs/sources_1/ip/axis_data_fifo_0/axis_data_fifo_0.xci
# IP: The module: 'axis_data_fifo_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/yunhao/Documents/ECE532-Digital-Systems-Design/ECE532-main/custom_ip/superresolution/superresolution.srcs/sources_1/ip/axis_data_fifo_0/axis_data_fifo_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_data_fifo_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/yunhao/Documents/ECE532-Digital-Systems-Design/ECE532-main/custom_ip/superresolution/superresolution.srcs/sources_1/ip/axis_data_fifo_0/axis_data_fifo_0/axis_data_fifo_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_data_fifo_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
