name: ece532
channels:
  - pytorch
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - pip

  # Development
  - black
  - isort
  - pylint

  # Runtime
  - jupyter
  - matplotlib
  - numba
  - numpy
  - opencv
  - pillow
  - scipy
  - tqdm

  # PyTorch
  - pytorch
  - torchaudio
  - torchvision
