all:
	vivado -mode batch -source convolve_multi_in_multi_out.tcl -nojournal -nolog

clean:
	rm -rf .Xil xgui component.xml \
		convolve_multi_in_multi_out.xpr \
		convolve_multi_in_multi_out.cache \
		convolve_multi_in_multi_out.hw \
		convolve_multi_in_multi_out.ip_user_files \
		convolve_multi_in_multi_out.sim \
		convolve_multi_in_multi_out.srcs
