all:
	vivado -mode batch -source convolve_rgb.tcl -nojournal -nolog

clean:
	rm -rf .Xil xgui component.xml \
		convolve_rgb.xpr \
		convolve_rgb.cache \
		convolve_rgb.hw \
		convolve_rgb.ip_user_files \
		convolve_rgb.sim \
		convolve_rgb.srcs
