webtalk_init -webtalk_dir /home/yunhao/Documents/ECE532-Digital-Systems-Design/ECE532/systemverilog/conv_debug/project_1.sim/sim_1/behav/xsim/xsim.dir/process_ppm_image_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Mar 20 17:25:51 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "e6ca7adf-fde7-43eb-a73b-acd2b02db5b4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "628ef1e7fec04c509bbc3c8bcf99e8ff" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 22.04.4 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "13th Gen Intel(R) Core(TM) i7-13700" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3534.011 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "33.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key SystemVerilog -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key File_Counter -value "10" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "227 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "19 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "564" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "12" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "0.60_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "214888_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3133072651 -regid "" -xml /home/yunhao/Documents/ECE532-Digital-Systems-Design/ECE532/systemverilog/conv_debug/project_1.sim/sim_1/behav/xsim/xsim.dir/process_ppm_image_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/yunhao/Documents/ECE532-Digital-Systems-Design/ECE532/systemverilog/conv_debug/project_1.sim/sim_1/behav/xsim/xsim.dir/process_ppm_image_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/yunhao/Documents/ECE532-Digital-Systems-Design/ECE532/systemverilog/conv_debug/project_1.sim/sim_1/behav/xsim/xsim.dir/process_ppm_image_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
