# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Albert/Documents/GitHub/ECE532/test_system/vivado_proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_auto_us_2/hdmi_auto_us_2.xci
# IP: The module: 'hdmi_auto_us_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Albert/Documents/GitHub/ECE532/test_system/vivado_proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_auto_us_2/hdmi_auto_us_2_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_auto_us_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Albert/Documents/GitHub/ECE532/test_system/vivado_proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_auto_us_2/hdmi_auto_us_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_auto_us_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/Albert/Documents/GitHub/ECE532/test_system/vivado_proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_auto_us_2/hdmi_auto_us_2.xci
# IP: The module: 'hdmi_auto_us_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Albert/Documents/GitHub/ECE532/test_system/vivado_proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_auto_us_2/hdmi_auto_us_2_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_auto_us_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Albert/Documents/GitHub/ECE532/test_system/vivado_proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_auto_us_2/hdmi_auto_us_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_auto_us_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
