# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ece532/ECE532/test_system/vivado_proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_superresolution_0_0/hdmi_superresolution_0_0.xci
# IP: The module: 'hdmi_superresolution_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/ece532/ECE532/test_system/vivado_proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_superresolution_0_0/ip/xbip_dsp48_macro_0/xbip_dsp48_macro_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xbip_dsp48_macro_0 || ORIG_REF_NAME==xbip_dsp48_macro_0} -quiet] -quiet

# IP: /home/ece532/ECE532/test_system/vivado_proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_superresolution_0_0/ip/xbip_dsp48_macro_1/xbip_dsp48_macro_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xbip_dsp48_macro_1 || ORIG_REF_NAME==xbip_dsp48_macro_1} -quiet] -quiet

# IP: /home/ece532/ECE532/test_system/vivado_proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_superresolution_0_0/ip/axis_data_fifo_0/axis_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_data_fifo_0 || ORIG_REF_NAME==axis_data_fifo_0} -quiet] -quiet

# XDC: /home/ece532/ECE532/test_system/vivado_proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_superresolution_0_0/ip/axis_data_fifo_0/axis_data_fifo_0_ooc.xdc

# XDC: /home/ece532/ECE532/test_system/vivado_proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_superresolution_0_0/ip/axis_data_fifo_0/axis_data_fifo_0/axis_data_fifo_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axis_data_fifo_0 || ORIG_REF_NAME==axis_data_fifo_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/ece532/ECE532/test_system/vivado_proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_superresolution_0_0/ip/axis_data_fifo_0/axis_data_fifo_0/axis_data_fifo_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axis_data_fifo_0 || ORIG_REF_NAME==axis_data_fifo_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# IP: /home/ece532/ECE532/test_system/vivado_proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_superresolution_0_0/hdmi_superresolution_0_0.xci
# IP: The module: 'hdmi_superresolution_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/ece532/ECE532/test_system/vivado_proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_superresolution_0_0/ip/xbip_dsp48_macro_0/xbip_dsp48_macro_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xbip_dsp48_macro_0 || ORIG_REF_NAME==xbip_dsp48_macro_0} -quiet] -quiet

# IP: /home/ece532/ECE532/test_system/vivado_proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_superresolution_0_0/ip/xbip_dsp48_macro_1/xbip_dsp48_macro_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xbip_dsp48_macro_1 || ORIG_REF_NAME==xbip_dsp48_macro_1} -quiet] -quiet

# IP: /home/ece532/ECE532/test_system/vivado_proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_superresolution_0_0/ip/axis_data_fifo_0/axis_data_fifo_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_data_fifo_0 || ORIG_REF_NAME==axis_data_fifo_0} -quiet] -quiet

# XDC: /home/ece532/ECE532/test_system/vivado_proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_superresolution_0_0/ip/axis_data_fifo_0/axis_data_fifo_0_ooc.xdc

# XDC: /home/ece532/ECE532/test_system/vivado_proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_superresolution_0_0/ip/axis_data_fifo_0/axis_data_fifo_0/axis_data_fifo_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axis_data_fifo_0 || ORIG_REF_NAME==axis_data_fifo_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/ece532/ECE532/test_system/vivado_proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_superresolution_0_0/ip/axis_data_fifo_0/axis_data_fifo_0/axis_data_fifo_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axis_data_fifo_0 || ORIG_REF_NAME==axis_data_fifo_0} -quiet] {/inst } ]/inst ] -quiet] -quiet
