name: ece532-srcnn
channels:
  - pytorch
  - nvidia
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - black
  - isort
  - jupyter
  - matplotlib
  - numpy
  - opencv
  - pandas
  - pillow
  - pylint
  - pytorch
  - pytorch-cuda=12.1
  - scikit-learn
  - scipy
  - tensorflow-cpu
  - tensorflow-datasets
  - torchaudio
  - torchvision
  - tqdm
